README.md
=> Add team name in README and remove instructions

README.md
=> docs: Add team name in README and remove instructions

server/.babelrc, server/configs/config.js, server/index.js, server/package.json, server/routes/boards.js, server/routes/users.js, server/yarn.lock
Add babel and nodemon to use ES6 features.
Also, add dummy GET /users and GET /boards routes.
Resolves #4
=> Add babel to server-side

.circleci/config.yml, package.json, server/package.json
Dummy Implementation:
Resolves #2
=> circle-ci for CI 

client/package.json, client/src/index.css, client/src/index.js, client/yarn.lock
=> Setup blueprintjs instead of reactstrap

.eslintrc.json, .gitignore, client/package.json, client/src/App.js, client/src/App.test.js, client/src/setupTests.js, client/yarn.lock, package.json, server/configs/config.js, server/package.json, server/routes/boards.js, server/routes/boards.test.js, server/yarn.lock, yarn.lock
Resolve #38 
Client Test using Shallow and Jest
Server test using Jest
=> chore: Setup jest and enzyme

Procfile, package.json, server/package.json
=> Add Procfile

server/models/board.js, server/models/comment.js, server/models/issue.js, server/models/lifecycle.js, server/models/user.js
=> feat: Create database schema

client/src/Components/Navbar/Navbar.js, client/src/Components/Navbar/Navbar.test.js
=> Add Navbar Component

client/src/App.js, client/src/App.test.js, client/src/components/Board/BoardBox.css, client/src/components/Board/BoardBox.js, client/src/components/Board/BoardBox.test.js
=> feat: Create a component for a new board

client/src/assets/CommentIcon.js, client/src/components/Comment/Comment.js, client/src/components/Comment/Comment.module.css, client/src/components/Comment/Comment.test.js
=> feat: Add comment component

client/src/components/Label/Label.js, client/src/components/Label/Label.test.js
=> feat: Add label component

client/src/assets/UpvoteIcon.js, client/src/components/Comment/Comment.js, client/src/components/Comment/Comment.test.js, client/src/components/Label/Label.js, client/src/components/Upvote/Upvote.js, client/src/components/Upvote/Upvote.test.js
Resolves #86 
Bug resolution: Changed the condition of existence of `condensed` prop received in `Comments` component.
=> Bugfix in React components: Upvote, Comment and Label

client/src/components/Assignee/Assignee.js, client/src/components/Assignee/Assignee.module.css, client/src/components/Assignee/Assignee.test.js
=> Create Assignee component

client/src/components/DueDate/DueDate.js, client/src/components/DueDate/DueDate.module.css, client/src/components/DueDate/DueDate.test.js
=> Create DueDate component

client/src/components/InviteUser/InviteUser.js, client/src/components/InviteUser/InviteUser.test.js
=> feat: Create modal to invite new user

client/src/components/UsersListModal/Users.css, client/src/components/UsersListModal/Users.js, client/src/components/UsersListModal/Users.test.js, client/src/components/UsersListModal/UsersListModal.js
=> feat: Modal to view User List

client/src/components/MemberList/MemberList.js, client/src/components/MemberList/MemberList.test.js
=> feat: Create Member List button

client/src/components/KanbanTitleBar/KanbanTitleBar.js, client/src/components/KanbanTitleBar/KanbanTitleBar.test.js
=> feat: Kanban Title Bar

client/src/components/CreateBoardModal/CreateBoardModal.js, client/src/components/CreateBoardModal/CreateBoardModal.test.js, client/src/components/CreateBoardModal/Lifecycle.js
=> feat: Create a modal for creating new Board

client/src/components/Issue/Issue.js, client/src/components/Issue/Issue.module.css, client/src/components/Issue/Issue.test.js
=> Create Issue card

server/.babelrc, server/configs/config.js, server/configs/httpStatusCodes.js, server/index.js, server/package.json, server/routes/boards.js, server/routes/boards.test.js
=> Add GET /boards/kanban route

server/index.js, server/package.json, server/routes/issues.js, server/routes/issues.test.js
=> Add POST /issues route

server/package.json, server/routes/boards.test.js, server/routes/issues.js, server/routes/issues.test.js, server/yarn.lock
=> GET /issues/issueid

server/routes/issues.js, server/routes/issues.test.js
=> feat: Add PATCH /issues/issueid/assignee route

server/routes/issues.js, server/routes/issues.test.js
=> Add PATCH /issues/issueid/duedate route

client/package.json, client/src/components/GoogleSignIn/GoogleSignIn.js, client/src/components/UsersListModal/Users.js, client/src/config.js, client/src/containers/SignUp/SignUp.js, client/src/index.js, client/yarn.lock, server/configs/config.js, server/configs/passport-setup.js, server/index.js, server/package.json, server/routes/auth-routes.js, server/yarn.lock
I'm able to login, and create a User in the database, the flow works when I'm testing this on the server but I'm unsure on how to actually write a test for this ,since the setup is using passport js which is a middleware.
Should I just do a mock up of an http request somewhere?
I was thinking of implementing client side as well, once the entire cycle is complete i:e UI & backend probably I can write test cases then.
Kindly help!
=> feat : Setup server authentication using passport.js

client/src/components/IssueDetailsModal/IssueDetails.css, client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/IssueDetailsModal/IssueDetails.test.js
=> feat: Modal to display issue details

server/models/issue.js, server/routes/boards.js, server/routes/issues.js, server/routes/issues.test.js
=> Add POST /issues/issueid/comment route

client/src/App.js, client/src/components/Lifecycle/Lifecycle.js, client/src/components/Lifecycle/Lifecycle.module.css, client/src/components/Lifecycle/Lifecycle.test.js, client/src/containers/KanbanLayout/KanbanLayout.js, client/src/containers/KanbanLayout/KanbanLayout.test.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.module.css, client/src/containers/LifecyclesContainer/LifecyclesContainer.test.js
=> Created KanbanLayout and Lifecycle React components

client/src/components/Lifecycle/Lifecycle.js, client/src/components/NewIssue/NewIssue.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.js
Reverts pesto-students/batch-7-Scryptonian#117
=> Revert "Add functionality to New Issue component"

client/src/components/Issue/Issue.js, client/src/components/KanbanTitleBar/KanbanTitleBar.js, client/src/components/Lifecycle/Lifecycle.js, client/src/components/Lifecycle/Lifecycle.test.js, client/src/components/NewIssue/NewIssue.js, client/src/components/NewIssue/NewIssue.module.css, client/src/config.js, client/src/containers/KanbanLayout/KanbanLayout.js, client/src/containers/KanbanLayout/KanbanLayout.test.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.js
=> Integrate frontend and backend to create Kanban Layout

client/src/components/Issue/Issue.js, client/src/components/KanbanTitleBar/KanbanTitleBar.js, client/src/components/Lifecycle/Lifecycle.js, client/src/components/Lifecycle/Lifecycle.test.js, client/src/components/NewIssue/NewIssue.js, client/src/components/NewIssue/NewIssue.module.css, client/src/config.js, client/src/containers/KanbanLayout/KanbanLayout.js, client/src/containers/KanbanLayout/KanbanLayout.test.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.js
=> Integrate frontend and backend

server/routes/issues.js, server/routes/issues.test.js
=> Add PATCH /issues/:issueid/upvote route

client/package.json, client/src/App.js, client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/IssueDetailsModal/IssueDetails.test.js, client/src/components/PickDate/PickDate.js, client/src/components/PickDate/PickDate.scss, client/yarn.lock
**On clicking:**
**On selecting a Date:
**
=> feat: Add duedate component

client/package.json, client/src/App.js, client/src/App.test.js, client/src/actions/actionDispatchers.js, client/src/actions/actionDispatchers.test.js, client/src/actions/actionTypes.js, client/src/components/Navbar/Navbar.js, client/src/components/Navbar/Navbar.test.js, client/src/config.js, client/src/containers/BoardView/BoardView.js, client/src/index.css, client/src/reducers/reducers.js, client/src/reducers/reducers.test.js, client/yarn.lock, server/routes/boards-routes.js, server/routes/boards.test.js
=> Navbar component added & integrated with redux

client/src/components/Issue/Issue.js, client/src/components/Issue/Issue.test.js, client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/Lifecycle/Lifecycle.js, client/src/components/NewIssue/NewIssue.js, client/src/components/Upvote/Upvote.js, client/src/components/Upvote/Upvote.test.js, client/src/reducers/reducers.js, client/src/reducers/reducers.test.js, server/routes/issues.js
=> Add complete functionality of upvoting an issue

client/src/components/CreateBoardModal/CreateBoardModal.js, client/src/containers/BoardLayout/BoardLayout.js, client/src/reducers/reducers.js, client/src/reducers/reducers.test.js, server/routes/auth-routes.js, server/routes/boards-routes.js
=> Integrate board route api on frontend

client/package.json, client/src/App.js, client/src/actions/actionDispatchers.js, client/src/components/Board/BoardBox.css, client/src/components/Board/BoardBox.js, client/src/components/Board/BoardBox.test.js, client/src/components/CreateBoardModal/CreateBoardModal.js, client/src/components/Footer/Footer.css, client/src/components/Footer/Footer.js, client/src/components/Navbar/Navbar.css, client/src/components/Navbar/Navbar.js, client/src/components/Navbar/Navbar.test.js, client/src/containers/BoardLayout/BoardLayout.js, client/src/containers/SignUp/SignUp.js, client/src/index.css, client/src/reducers/reducers.js, client/src/reducers/reducers.test.js, server/routes/auth-routes.js, server/routes/boards-routes.js
Resolves #156 
- Enchance Board UI 
- Fixed warning in various files 
- Added Footer
=> Enhance Board page User Interface

client/package.json, client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/LabelsComponent/Labels.css, client/src/components/LabelsComponent/Labels.js, client/yarn.lock
=> feat: Component to add labels to Issue

client/src/components/IssueDetailsModal/IssueDetails.js, server/routes/issues-routes.js
=> Add functionality to delete comments

client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/PickDate/PickDate.js, client/src/components/PickDate/PickDate.scss, server/routes/issues-routes.js
=> Add functionality to set due date to an issue

server/middlewares/userRoleCheck.js, server/routes/boards-routes.js
=> Add route to delete a board

client/src/components/DeleteConfirmation/DeleteConfirmation.js, client/src/components/DeleteConfirmation/DeleteConfirmation.module.css, client/src/components/IssueDetailsModal/IssueDetails.js, server/middlewares/userRoleCheck.js, server/models/issue.js, server/routes/boards-routes.js, server/routes/issues-routes.js
=> Add functionality to delete an issue

client/src/App.js, client/src/assets/UpvoteIcon.js, client/src/components/Comment/Comment.module.css, client/src/components/Issue/Issue.js, client/src/components/Issue/Issue.module.css, client/src/components/Lifecycle/Lifecycle.js, client/src/components/Lifecycle/Lifecycle.module.css, client/src/components/NewIssue/NewIssue.js, client/src/components/NewIssue/NewIssue.module.css, client/src/components/NewIssue/NewIssue.test.js, client/src/components/Upvote/Upvote.module.css, client/src/containers/LifecyclesContainer/LifecyclesContainer.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.module.css, client/src/index.css, server/routes/boards-routes.js
=> Enchance kanban layout UI 

client/src/App.js, server/configs/passport-setup.js, server/models/user.js, server/routes/boards-routes.js
=> Add POST /boards/:boardid/invite route

client/package.json, client/src/config.js, server/index.js
Reverts pesto-students/batch-7-Scryptonian#186
=> Revert "Add Proxy"

client/src/App.js, client/src/components/Assignee/Assignee.module.css, client/src/components/Lifecycle/Lifecycle.js, client/src/components/Lifecycle/Lifecycle.module.css, client/src/components/Navbar/Navbar.css, client/src/components/Navbar/Navbar.js, client/src/components/Navbar/Navbar.test.js, client/src/containers/KanbanLayout/KanbanLayout.js, client/src/containers/KanbanLayout/KanbanLayout.test.js, client/src/containers/LifecyclesContainer/LifecyclesContainer.module.css, client/src/index.css
=> Merge kanban title bar & navbar

client/src/actions/actionDispatchers.js, client/src/axios.js, client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/PickDate/PickDate.js, client/src/containers/BoardLayout/BoardLayout.js, client/src/index.js, server/index.js, server/middlewares/authService.js, server/middlewares/userRoleCheck.js, server/routes/boards-routes.js, server/routes/boards.test.js, server/routes/issues-routes.js
=> Remove cors workaround

client/src/components/Board/BoardBox.js, client/src/components/Board/DeleteBoard.js, client/src/components/Board/EditBoard.js, client/src/components/Board/EditButtonPopover.js, client/src/components/IssueDetailsModal/IssueDetails.js, client/src/components/UsersListModal/Users.js, client/src/containers/BoardLayout/BoardLayout.js
=> Edit and Delete Board Functiobality
